version: '3.7'
services:
  app-tests:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.tests
    environment:
      app.url: http://app:8000
      spreaker.url: http://wiremock:8080

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      PORT: 8000

  wiremock:
    image: wiremock/wiremock
