version: '3.7'
services:
  app-tests:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.tests
    environment:
      prop.app.url: http://app:8000
      prop.spreaker.url: http://spreaker:8080
      prop.spreaker.title_limit: 140
      prop.google.url: http://google:8080
      prop.wikipedia.url: http://en.wikipedia.org:8080
      prop.TODAY: "2017-01-05"
    depends_on:
    - app
    - spreaker
    - google
    - en.wikipedia.org

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      PORT: 8000
      TODAY: "2017-01-05"

  spreaker:
    image: docker.io/wiremock/wiremock

  google:
    image: docker.io/wiremock/wiremock

  en.wikipedia.org:
    image: docker.io/wiremock/wiremock
    entrypoint: ["/docker-entrypoint.sh", "--verbose"]

